services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: stack-sql-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stack_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_pgvector:/var/lib/postgresql/data